### ISSUE TITLE
Login/Register Issue

### ISSUE THREAD

**Issue by JAePortfolio** [alexmat2on/MEEP#8]
Register page makes an account and logs you directly in.
On login page, it will tell you login failed with the account you just made on the register page.

**Comment by JAePortfolio** [comment]
login error Error: "Request failed with status code 403"
createErrorwebpack:///./node_modules/axios/lib/core/createError.js?:16:15

settlewebpack:///./node_modules/axios/lib/core/settle.js?:18:12

handleLoadwebpack:///./node_modules/axios/lib/adapters/xhr.js?:77:7

**Comment by alexmat2on** [comment]
Did you figure this out? I'm not sure what the problem could be

**Comment by JAePortfolio** [comment]
Hay I sent you a text. Unfortunately not, it was working just fine for me yesterday :(

**Comment by JAePortfolio** [comment]
Seems to be working now. :)
